### ISSUE TITLE
The Pop Shop almost always freezes when I search for an app, making the whole DE crash.

### ISSUE THREAD

**Issue by filnstuff** [pop-os/shop#337] opened 2022-03-26 10:35 UTC
**Distribution: Pop!_OS 21.10**
 
 
 
**Related Application: Latest Pop!_shop version**

**Issue/Bug Description:This happens when I search for an application or when I pick a category. The whole program freezes and a few seconds later the entire OS is unresponsive. I always have to manually restart my pc **

**Steps to reproduce (if you know): type an app name in the search box at a normal typing speed**

**Expected behavior:**

**Other Notes: 
filippo@pop-os 
-------------- 
OS: Pop!_OS 21.10 x86_64 
Host: Nitro AN515-52 V1.24 
Kernel: 5.16.11-76051611-generic 
Uptime: 10 mins 
Packages: 1892 (dpkg), 17 (flatpak) 
Shell: bash 5.1.8 
Resolution: 1920x1080 
DE: GNOME 40.5 
WM: Mutter 
WM Theme: Pop 
Theme: Pop-dark [GTK2/3] 
Icons: Pop [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i5-8300H (8) @ 4.000GHz 
GPU: Intel CoffeeLake-H GT2 [UHD Graphics 630]
GPU: NVIDIA GeForce GTX 1050 Ti Mobile 
Memory: 1692MiB / 7789MiB 

**

**Comment by notgary-kunisweeb** [comment] 2022-03-27 04:23
Did you reset the system if so did the problems go away ??

**Comment by filnstuff** [comment] 2022-03-27 14:18
> 

I did, multiple times, and it still had this bug.
This is happening since December

**Comment by mmstick** [comment] 2022-03-27 14:24
Duplicate of #240

**Closed by mmstick** 2022-03-27 14:24 UTC
