### ISSUE TITLE
Unusable search bar while on Installed tab

### ISSUE THREAD

**Issue by cj0nes** [pop-os/shop#259] opened 2021-02-20 14:38 UTC
**Distribution (run `cat /etc/os-release`):**
20.10 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
3.3.0pop0\~1607377061\~20.10~996e63e

**Issue/Bug Description:**
When on the Installed tab, the search bar is unusable. Unable to click into the search bar.

**Steps to reproduce (if you know):**
1. Open Pop!_Shop
2. Click Installed tab
3. Unable to click into search bar and use it

**Expected behavior:**
1. Open Pop!_Shop
2. Click Installed tab
3. Able to click into search bar and use it

**Other Notes:**

**Comment by leviport** [comment] 2021-02-22 14:56
Duplicate of https://github.com/pop-os/shop/issues/13

**Closed by leviport** 2021-02-22 14:56 UTC
