### ISSUE TITLE
Add support for back button

### ISSUE THREAD

**Issue by isantop** [pop-os/shop#19] opened 2017-10-10 18:07 UTC
Some Mice/Keyboards offer a back button (e.g. for going back in the browser and file managers, etc.). This should be supported in Pop_Shop too, since we have a generic back button action. Should be as simple as looking for that signal and tying it to the back button.

**Comment by cassidyjames** [comment] 2017-10-20 21:41
Dupe of upstream bug https://github.com/elementary/appcenter/issues/23, not sure if we want to leave this one open or not.

**Comment by isantop** [comment] 2017-10-20 21:42
We should leave it open until the upstream bug is closed.

**Closed** 2017-12-20 23:07 UTC
Labels: upstream, wishlist
