### ISSUE TITLE
Search Doesn't Work When In App Page

### ISSUE THREAD

**Issue by thistechguy** [pop-os/shop#277] opened 2021-07-06 13:37 UTC
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os

**Issue/Bug Description:**
When in the Pop Shop, I can search from the main home screen or in the search results. But if I'm in an App page, the search functionality doesn't work. I cannot click on the search bar and I have to return to the search results in order to search again.

![image](https://user-images.githubusercontent.com/86990020/124609594-c38b7500-de3d-11eb-8370-ca85b09ce20e.png)

**Steps to reproduce (if you know):**
Search for application in Pop Shop. Select app from search results. Click on search bar while in app page and cannot click on search bar until returning to search results.

**Expected behavior:**
I would expect to have the ability to search anywhere in the Pop Shop, especially in the app page.

**Other Notes:**

**Comment by cassidyjames** [comment] 2021-07-06 16:31
Duplicate of #46 and https://github.com/elementary/appcenter/issues/493

**Comment by ahoneybun** [comment] 2021-09-03 20:53
Duplicate of #13

**Closed by ahoneybun** 2021-09-03 20:53 UTC
