### ISSUE TITLE
Updating the system destroys built in display brightness control

### ISSUE THREAD

**Issue by John15321** [pop-os/shop#329] opened 2022-02-22 19:00 UTC
**Distribution (run `cat /etc/os-release`):**
 
 ```bash
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```bash
system76-driver-nvidia:
  Installed: 20.04.48~1643752136~21.10~8120238
  Candidate: 20.04.48~1643752136~21.10~8120238
  Version table:
 *** 20.04.48~1643752136~21.10~8120238 1001
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
       1001 http://apt.pop-os.org/release impish/main i386 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**

I updated my system via Pop Shop, it updated some things relating to nvidia drivers. After doing so I cannot change my screen brightness (I have a Lenovo laptop). I found someone with a similar issue online but from a few years ago, in their case installing `system76-driver-nvidia` helped, so I tried doing that. Althought it did install, it didn't help. Additionally I got a warning during the installation that my vendor, that is Lenovo, is not recognized which seems to be a bug:

```bash
Created symlink /etc/systemd/system/multi-user.target.wants/system76-firmware-da
emon.service → /lib/systemd/system/system76-firmware-daemon.service.
Setting up system76-driver (20.04.48~1643752136~21.10~8120238) ...
WARNING	invalid sys_vendor: 'LENOVO'
WARNING	invalid product_version: None
Created symlink /etc/systemd/system/multi-user.target.wants/system76-driver.serv
ice → /lib/systemd/system/system76-driver.service.
Processing triggers for dbus (1.12.20-2ubuntu2) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu2) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for libglib2.0-0:amd64 (2.68.4-1ubuntu1) ...
Processing triggers for libc-bin (2.34-0ubuntu3) ...
Processing triggers for man-db (2.9.4-2) ...
Setting up system76-driver-nvidia (20.04.48~1643752136~21.10~8120238) ...
INFO:Enable system76-driver-nvidia
```

**Steps to reproduce (if you know):**

I regularly update my system. I just clicked the update button for my system on Pop Shop:

![image](https://user-images.githubusercontent.com/56229312/155200234-fbf9eb01-156b-4281-b2d8-8e7ba78c07e1.png)

**Expected behavior:**

Brightness control should work

**Other Notes:**

<details>
<summary>My other system info:
</summary>

```bash
System:    Host: pop-os Kernel: 5.15.23-76051523-generic x86_64 bits: 64 compiler: gcc v: 11.2.0 Desktop: GNOME 40.5 
           tk: GTK 3.24.30 wm: gnome-shell dm: GDM3 41.rc Distro: Pop!_OS 21.10 base: Ubuntu Impish 
Machine:   Type: Laptop System: LENOVO product: 82B1 v: Lenovo Legion 5 15ARH05H serial: <superuser required> Chassis: 
           type: 10 v: Lenovo Legion 5 15ARH05H serial: <superuser required> 
           Mobo: LENOVO model: LNVNB161216 v: NO DPK serial: <superuser required> UEFI: LENOVO v: FSCN18WW date: 01/01/2021 
Battery:   ID-1: BAT0 charge: 35.5 Wh (60.0%) condition: 59.2/60.0 Wh (98.6%) volts: 15.9 min: 15.4 model: SMP L19M4PC0 
           type: Li-poly serial: 4613 status: Unknown cycles: 34 
CPU:       Info: 8-Core model: AMD Ryzen 7 4800H with Radeon Graphics bits: 64 type: MT MCP arch: Zen 2 rev: 1 cache: 
           L2: 4 MiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 92630 
           Speed: 1470 MHz min/max: 1400/2900 MHz boost: enabled Core speeds (MHz): 1: 1470 2: 1521 3: 1898 4: 1908 5: 1908 
           6: 1903 7: 4280 8: 4292 9: 1575 10: 1479 11: 3220 12: 2554 13: 1796 14: 1748 15: 3011 16: 2870 
Graphics:  Device-1: NVIDIA TU116M [GeForce GTX 1660 Ti Mobile] vendor: Lenovo driver: nvidia v: 510.54 bus-ID: 01:00.0 
           chip-ID: 10de:2191 class-ID: 0300 
           Device-2: Advanced Micro Devices [AMD/ATI] Renoir vendor: Lenovo driver: amdgpu v: kernel bus-ID: 05:00.0 
           chip-ID: 1002:1636 class-ID: 0300 
           Device-3: Syntek Integrated Camera type: USB driver: uvcvideo bus-ID: 3-3:5 chip-ID: 174f:244c class-ID: 0e02 
           serial: 0001 
           Display: x11 server: X.Org 1.20.13 compositor: gnome-shell driver: loaded: amdgpu,ati,nvidia 
           unloaded: fbdev,modesetting,nouveau,vesa resolution: 1: 2560x1440~75Hz 2: 2560x1440~75Hz 3: 1920x1080~144Hz 
           s-dpi: 122 
           OpenGL: renderer: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2 v: 4.6.0 NVIDIA 510.54 direct render: Yes 
Audio:     Device-1: NVIDIA TU116 High Definition Audio driver: snd_hda_intel v: kernel bus-ID: 01:00.1 chip-ID: 10de:1aeb 
           class-ID: 0403 
           Device-2: Advanced Micro Devices [AMD] Raven/Raven2/FireFlight/Renoir Audio Processor vendor: Lenovo driver: N/A 
           bus-ID: 05:00.5 chip-ID: 1022:15e2 class-ID: 0480 
           Device-3: Advanced Micro Devices [AMD] Family 17h HD Audio vendor: Lenovo driver: snd_hda_intel v: kernel 
           bus-ID: 05:00.6 chip-ID: 1022:15e3 class-ID: 0403 
           Sound Server-1: ALSA v: k5.15.23-76051523-generic running: yes 
           Sound Server-2: PulseAudio v: 15.0 running: yes 
           Sound Server-3: PipeWire v: 0.3.32 running: yes 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Lenovo driver: r8169 v: kernel port: 2000 
           bus-ID: 03:00.0 chip-ID: 10ec:8168 class-ID: 0200 
           IF: eno1 state: up speed: 1000 Mbps duplex: full mac: 38:f3:ab:15:ae:22 
           Device-2: Intel Wi-Fi 6 AX200 driver: iwlwifi v: kernel port: 2000 bus-ID: 04:00.0 chip-ID: 8086:2723 
           class-ID: 0280 
           IF: wlp4s0 state: up mac: b4:0e:de:4c:bb:8e 
           IF-ID-1: virbr0 state: down mac: 52:54:00:d6:4d:47 
Bluetooth: Device-1: Intel AX200 Bluetooth type: USB driver: btusb v: 0.8 bus-ID: 5-3:3 chip-ID: 8087:0029 class-ID: e001 
           Report: hciconfig ID: hci0 rfk-id: 2 state: up address: B4:0E:DE:4C:BB:92 bt-v: 3.0 lmp-v: 5.2 sub-v: 27a4 
           hci-v: 5.2 rev: 27a4 
Drives:    Local Storage: total: 1.49 TiB used: 280.53 GiB (18.4%) 
           ID-1: /dev/nvme0n1 vendor: SK Hynix model: HFM512GDHTNI-87A0B size: 476.94 GiB speed: 31.6 Gb/s lanes: 4 type: SSD 
           serial: NJ12N513411502B79 rev: 11020C00 temp: 33.9 C scheme: GPT 
           ID-2: /dev/sda vendor: Crucial model: CT1000MX500SSD1 size: 931.51 GiB speed: 6.0 Gb/s type: SSD 
           serial: 1919E20206DF rev: 023 temp: 40 C scheme: GPT 
           ID-3: /dev/sdb type: USB vendor: Samsung model: Flash Drive size: 119.51 GiB type: SSD serial: 0330219120002036 
           rev: 1100 scheme: MBR 
Partition: ID-1: / size: 907.44 GiB used: 239.37 GiB (26.4%) fs: ext4 dev: /dev/dm-1 mapped: data-root 
           ID-2: /boot/efi size: 497 MiB used: 238.8 MiB (48.1%) fs: vfat dev: /dev/sda1 
Swap:      ID-1: swap-1 type: partition size: 4 GiB used: 0 KiB (0.0%) priority: -2 dev: /dev/dm-2 mapped: cryptswap 
Sensors:   Message: No sensor data found. Is lm-sensors configured? 
Info:      Processes: 505 Uptime: 17m wakeups: 1 Memory: 30.8 GiB used: 6.09 GiB (19.8%) Init: systemd v: 248 runlevel: 5 
           Compilers: gcc: 11.2.0 alt: 11/9 Packages: 2412 apt: 2357 flatpak: 52 snap: 3 Shell: Zsh v: 5.8 running-in: tilix 
           inxi: 3.3.06 
```

</details>

**Comment by leviport** [comment] 2022-02-23 23:02
Closing as a duplicate of https://github.com/pop-os/pop/issues/2197

Looks like https://github.com/pop-os/pop/issues/2227 is also related or the same.

**Closed by leviport** 2022-02-23 23:02 UTC
