### ISSUE TITLE
Deformed grid of buttons on Pop-shop

### ISSUE THREAD

**Issue by KJ2ME** [pop-os/shop#183] opened 2020-05-03 07:48 UTC
**Distribution (run `cat /etc/os-release`):**

Pop_OS! 20.04

**Issue/Bug Description:**

The uninstall and source button overflow the space for these.

Screencapture: https://i.imgur.com/56L9iJB.png

**Comment by leviport** [comment] 2020-05-04 18:11
Thanks for the report. That's actually because another button is supposed to go there, but is disappearing after install. We're tracking that bug here: https://github.com/pop-os/shop/issues/174


Duplicate of: https://github.com/pop-os/shop/issues/174

**Closed by leviport** 2020-05-04 18:11 UTC
