### ISSUE TITLE
Search does not work when on "updates" tab

### ISSUE THREAD

**Issue by jasonmccallister** [pop-os/shop#21] opened 2017-10-30 05:46 UTC
While this may make sense to not allows the "updates" tab to searchable, the search field still remains but is unusable. My first reaction is to click into the search field to being typing, but clicking on the search field does nothing.

Ideally the search field would work and start a new search for the store. I would argue against removing the field when _only_ on the updates tab as this would feel like an inconsistency in the UI.

Note: This appears to be related, but it seems that when I open shop I am frequently sent to the updates tab (pretty sure same issue as #14).

**Comment by isantop** [comment] 2017-10-31 17:08
We'll need to figure out how exactly search will work in Pop_OS. There is a small lack of clarity about _what_ would be searched on the updates tab, which is why it's currently disabled.

**Comment by brs17** [comment] 2019-03-28 14:54
I believe this is a duplicate of https://github.com/pop-os/shop/issues/13 so I am going to close it.

**Closed by brs17** 2019-03-28 14:54 UTC
Labels: confirmed
