### ISSUE TITLE
Pop!_Shop always opens in the "Installed" page

### ISSUE THREAD

**Issue by hyuri** [pop-os/shop#314] opened 2021-12-19 17:13 UTC
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish

**Issue/Bug Description:**
Every time I open Pop!_Shop, either by clicking on the icon, or from the Launcher, it switches to the "Installed" page and starts checking for updates.

**Steps to reproduce (if you know):**
1. Click on Pop!_Shop icon, or run it from the Launcher.

**Expected behavior:**
Pop!_Shop should open in the Home page unless I'm opening it from an "Updates Available" notification.

More often than not, I'm opening Pop!_Shop to find an app to install. In that case, I want to open it, press Ctrl + F to switch the focus to the search bar, type the name of the app I'm looking for, and proceed from there.

**Comment by hyuri** [comment] 2021-12-19 17:54
Ok... I've been using Pop!_OS for 2 days now, and the whole time this bug has been happening, but now that I decide to report it, it seems to have magically fixed itself... Holy weirdamole🤨️

At least for this session. I'll see what happens next time I reboot.

**Comment by hyuri** [comment] 2021-12-19 17:59
Nah, now this weird workspace bug is happening.

![image](https://user-images.githubusercontent.com/18584014/146685531-0e0b0265-807e-4e60-bf7b-458353b41196.png)

**Comment by jacobgkau** [comment] 2023-10-02 15:52
Duplicate of https://github.com/pop-os/shop/issues/14.

**Closed by jacobgkau** 2023-10-02 15:52 UTC
