### ISSUE TITLE
Can't search when on "Installed Tab" of Pop OS.

### ISSUE THREAD

**Issue by titojankowski** [pop-os/shop#285] opened 2021-09-03 16:54 UTC
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
It's the Pop Shop itself

**Issue/Bug Description:**
Bug: Can't search when on "Installed Tab" of Pop OS.

**Steps to reproduce (if you know):**

Steps to replicate:
Open Pop!_Shop
Go to "Installed" tab
Click in "Search Apps" box
Nothing happens, can't enter text in the box.
Same thing when within an Application's page in the shop (ie an application I just installed or an application found through the Home page)

Version: POP 21.04, just bought this computer and it's been like that since the start.

**Expected behavior:**
I would expect to be able to enter text in the box.

**Other Notes:**
I am a Mac user switching over. Not a developer.

**Comment by leviport** [comment] 2021-09-03 18:31
Duplicate of https://github.com/pop-os/shop/issues/13

**Closed by leviport** 2021-09-03 18:31 UTC
