### ISSUE TITLE
I am not able to search using the search bar when I am on the Installed apps page 

### ISSUE THREAD

**Issue by Amazeryogo** [pop-os/shop#229] opened 2020-10-11 09:01 UTC
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS Version 20.04 LTS 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Pop!_Shop

**Issue/Bug Description:**
I am not able to search using the search bar when I am on the Installed apps page 

**Steps to reproduce (if you know):**
In Pop!_Shop, there are two buttons on top, Home and Installed
Click on Installed 
now try searching using the search bar 

**Expected behaviour:**
It should search the app.

**Other Notes:**
This also happens when I click on an app to see it's description (on pop!_shop)

**Comment by Amazeryogo** [comment] 2020-10-11 09:03
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

**Comment by leviport** [comment] 2020-10-12 14:22
Duplicate of: https://github.com/pop-os/shop/issues/13

**Closed by leviport** 2020-10-12 14:22 UTC
