### ISSUE TITLE
Pop!_shop freezes while looking for updates in the background.

### ISSUE THREAD

**Issue by vega-d** [pop-os/shop#280] opened 2021-07-26 15:20 UTC
**Distribution (run `cat /etc/os-release`):**
 ```NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
it's `io.elementary.appcenter` aka pop shop, I could not run apt policy on it for some reason.

**Issue/Bug Description:**
Pop!_Shop freezes while performing `apt update` in the background.

**Steps to reproduce (if you know):**
- Have slow internet connection.
- Open Pop!_shop.
- Try to do anything while it updates repos.

**Expected behavior:**
- No freezes, lol.

**Comment by PixsaOJ** [comment] 2021-09-20 05:04
Apparently, reinstalling OS fixes this problem 🤣

**Comment by PixsaOJ** [comment] 2021-09-20 05:07
https://github.com/pop-os/shop/issues/240 Here move to this

**Comment by mmstick** [comment] 2022-03-27 14:25
Duplicate of #240

**Closed by mmstick** 2022-03-27 14:25 UTC
