### ISSUE TITLE
Pop Shop insists in downgrading packages from other sources (VS Code)

### ISSUE THREAD

**Issue by lxbrito** [pop-os/shop#275] opened 2021-06-23 13:58 UTC
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
pop-shop:
  Installed: 3.4.2pop0~1622814255~21.04~2653c0f
  Candidate: 3.4.2pop0~1622814255~21.04~2653c0f
  Version table:
 *** 3.4.2pop0~1622814255~21.04~2653c0f 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
When using microsoft repo for code ("VS Code") it insists in sticking with older pop repo version. My settings are to stick with newest version and I even locked package version, but it insists in downgrading the package.

The most bizarre is when I open pop shop it shows the pop repo version (in current case 1.56.x), and suddenly changes it to MS repo version 1.57.1 (the installed one). however if I click to "update" the package, it will install 1.56.x from Pop repo.

The package is locked at 1.57.1 and my settings are to choose the newest version

**Steps to reproduce (if you know):**
add repo http://packages.microsoft.com/repos/code/ stable main
install code
check versions and try to stick with the ms repo

**Expected behavior:**
Stick with the newest version and/or the locked one

**Other Notes:**

**Comment by leviport** [comment] 2021-06-23 15:13
Duplicate of https://github.com/pop-os/vscode/issues/3

**Closed by leviport** 2021-06-23 15:13 UTC
