### ISSUE TITLE
GUI shouldn't freeze when installs are actually making progress in the background

### ISSUE THREAD

**Issue by peey** [pop-os/shop#293] opened 2021-10-12 11:02 UTC
**Distribution (run `cat /etc/os-release`):**
 
```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

N/A

**Issue/Bug Description:**

I had a lot of installations (~20 pending updates, ~1 new installation, ~6 GB total), and after a while pop_shop hit 100% CPU usage and so the UI froze. 

I wanted to know if it has froze ([there seem to be multiple bug reports related to that already](https://github.com/pop-os/shop/issues?q=is%3Aissue+is%3Aopen+freeze)) or what. So I observed the top CPU usage programs for a while and I noticed that after pop_shop, these programs had highest CPU usage at different points in time:
-  `/usr/bin/dpkg` 
- `dpkg-deb` 
-  decompression programs at 100% CPU use 
- `/usr/lib/packagekit/pk-debconf-helper`
- `/usr/lib/packagekit/packagekitd`

The top CPU consuing-processes cycle between these.

So **I suspect that it's actually making progress**, it's just the GUI which has frozen. 

After a while I stopped seeing any discernible package installation activity so I killed pop_shop and restarted it. The only things which were still pending installation where

```
1 component with updates:
 • org.freedesktop.Platform Flatpak runtime
```

and the new app installs.

**Steps to reproduce (if you know):**

Update a lot of stuff at once after a long time

Then additionally hit install on a few new applications before updates are finished

**Expected behavior:**

GUI should report progress instead of freezing. It can display simplistic progress metrics instead of displaying detailed ones for all the packages being updated, if that makes it more feasible.

**Other Notes:**

**Comment by protodrew** [comment] 2021-11-23 02:38
agreeing with this, it also freezes for me when checking for updates or indexing because I searched for a package. Feels very slow and unresponsive.

**Comment by xerohackcom** [comment] 2021-11-28 03:28
I agree

**Comment by mmstick** [comment] 2022-03-27 14:25
Duplicate of #240

**Closed by mmstick** 2022-03-27 14:25 UTC
