### ISSUE TITLE
Inconsistent single/separate entries for flatpak and deb versions of the same app

### ISSUE THREAD

**Issue by axelmeunier** [pop-os/shop#203] opened 2020-07-20 13:59 UTC
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 20.04
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Pop shop

**Issue/Bug Description:**
Flatpak and deb versions of an application are sometimes filed as a single entry in Pop shop (then you can make a choice to install flatpak or deb), and sometimes filed as separate entries.
Examples of separate entries : VLC, Inkscape, Dropbox, Clementine, Libreoffice
Examples of single entry : Celluloid, Dconf, Geary, Telegram, Kdenlive

**Steps to reproduce (if you know):**
Open Pop Shop and search for the above mentioned apps. 

**Expected behavior:**
The behaviour should be consistent across apps.

**Other Notes:**

**Comment by cassidyjames** [comment] 2020-07-22 02:49
Duplicate of upstream issue: https://github.com/elementary/appcenter/issues/1011

And Pop!_Shop issue (which has seemingly turned into a catch-all): https://github.com/pop-os/shop/issues/157

**Closed** 2022-02-09 15:07 UTC
