### ISSUE TITLE
Pop Shop crashes if update fails

### ISSUE THREAD

**Issue by omalk98** [pop-os/shop#357] opened 2022-04-27 03:46 UTC
**Distribution (run `cat /etc/os-release`):**
 VERSION="22.04 LTS"
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
Pop Shop crashes and closes if an update is unable to be upgraded through APT

**Steps to reproduce (if you know):**
Currently ttf-mscorefonts-installer 3.8ubuntu2 has issues upgrading from 3.7 on default install of Pop!_Os 22.04, when upgrading through APT this generates the following upgrade error:

"the following packages have unmet dependencies:
 debconf : Breaks: update-notifier-common (< 3.187~) but 1.0.0~1650991095~22.04~9efdc50 is to be installed"

when upgrading through pop shop, the app simply crashes. 
Other apps failing to upgrade should have same/similar result

**Expected behavior:**
Get message with error or a box to indicate failed upgrade

**Comment by jacobgkau** [comment] 2022-05-31 14:52
Potentially related: https://github.com/pop-os/shop/issues/356, https://github.com/pop-os/shop/issues/353, https://github.com/pop-os/shop/issues/341.

**Comment by jacobgkau** [comment] 2022-05-31 14:53
Actually, this sounds like a duplicate of https://github.com/pop-os/shop/issues/341 in particular.

**Closed** 2022-05-31 14:56 UTC
