### ISSUE TITLE
Pop Shop not responding/get freezes

### ISSUE THREAD

**Issue by lllYlll-cyber** [pop-os/shop#246] opened 2021-01-16 04:30 UTC
**Distribution (run `cat /etc/os-release`):
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):
pop-shop:
Installed：3.3.0pop0~1607377061~20.10~996e63e
Candidate： 3.3.0pop0~1607377061~20.10~996e63e
Version table：
*** 3.3.0pop0~1607377061~20.10~996e63e 1001
1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
100 /var/lib/dpkg/status

**Issue/Bug Description: 
I can open Pop-shop, but after few seconds it just freezes and the notification is "Pop!-Shop is not responding", so I have to force quit it. However, if I right click pop-shop and select "Check for updates", it runs correctly until I select "Home" from "Installed" and then few seconds later it freezes again. 

When I started pop-shop from terminal, it shows something like this when it freezes:

** (io.elementary.appcenter:6320: Warning **: 12:24:37.478:  Package.vala:889: Package not found

**Steps to reproduce (if you know):
Open pop-shop and it will freezes

**Expected behavior:
Should work correctly/not freeze

**Other Notes:**
I've searched online and found out that a lot of people is having this issue but not be able to find a solution.

**Comment by leviport** [comment] 2021-01-19 15:07
Duplicate of https://github.com/pop-os/shop/issues/240

**Closed by leviport** 2021-01-19 15:07 UTC
