### ISSUE TITLE
Pop shop crashes when packages are kept back

### ISSUE THREAD

**Issue by GroobleDierne** [pop-os/shop#352] opened 2022-05-01 16:26 UTC
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Sorry the outputs are in french.
```
libnvidia-cfg1-510:
  Installé : 510.60.02-1pop0~1649099333~22.04~aedf526
  Candidat : 510.68.02-1pop0~1651161204~22.04~46a1f79
 Table de version :
     510.68.02-1pop0~1651161204~22.04~46a1f79 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
 *** 510.60.02-1pop0~1649099333~22.04~aedf526 100
        100 /var/lib/dpkg/status
     510.60.02-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages
libnvidia-extra-510:
  Installé : 510.60.02-1pop0~1649099333~22.04~aedf526
  Candidat : 510.68.02-1pop0~1651161204~22.04~46a1f79
 Table de version :
     510.68.02-1pop0~1651161204~22.04~46a1f79 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
 *** 510.60.02-1pop0~1649099333~22.04~aedf526 100
        100 /var/lib/dpkg/status
     510.60.02-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages
nvidia-compute-utils-510:
  Installé : 510.60.02-1pop0~1649099333~22.04~aedf526
  Candidat : 510.68.02-1pop0~1651161204~22.04~46a1f79
 Table de version :
     510.68.02-1pop0~1651161204~22.04~46a1f79 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
 *** 510.60.02-1pop0~1649099333~22.04~aedf526 100
        100 /var/lib/dpkg/status
     510.60.02-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages
nvidia-dkms-510:
  Installé : 510.60.02-1pop0~1649099333~22.04~aedf526
  Candidat : 510.68.02-1pop0~1651161204~22.04~46a1f79
 Table de version :
     510.68.02-1pop0~1651161204~22.04~46a1f79 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
 *** 510.60.02-1pop0~1649099333~22.04~aedf526 100
        100 /var/lib/dpkg/status
     510.60.02-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages
nvidia-kernel-source-510:
  Installé : 510.60.02-1pop0~1649099333~22.04~aedf526
  Candidat : 510.68.02-1pop0~1651161204~22.04~46a1f79
 Table de version :
     510.68.02-1pop0~1651161204~22.04~46a1f79 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
 *** 510.60.02-1pop0~1649099333~22.04~aedf526 100
        100 /var/lib/dpkg/status
     510.60.02-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages
nvidia-utils-510:
  Installé : 510.60.02-1pop0~1649099333~22.04~aedf526
  Candidat : 510.68.02-1pop0~1651161204~22.04~46a1f79
 Table de version :
     510.68.02-1pop0~1651161204~22.04~46a1f79 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
 *** 510.60.02-1pop0~1649099333~22.04~aedf526 100
        100 /var/lib/dpkg/status
     510.60.02-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages
xserver-xorg-video-nvidia-510:
  Installé : 510.60.02-1pop0~1649099333~22.04~aedf526
  Candidat : 510.68.02-1pop0~1651161204~22.04~46a1f79
 Table de version :
     510.68.02-1pop0~1651161204~22.04~46a1f79 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
 *** 510.60.02-1pop0~1649099333~22.04~aedf526 100
        100 /var/lib/dpkg/status
     510.60.02-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages
nvidia-driver-510:
  Installé : 510.60.02-1pop0~1649099333~22.04~aedf526
  Candidat : 510.68.02-1pop0~1651161204~22.04~46a1f79
 Table de version :
     510.68.02-1pop0~1651161204~22.04~46a1f79 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
 *** 510.60.02-1pop0~1649099333~22.04~aedf526 100
        100 /var/lib/dpkg/status
     510.60.02-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages
libnvidia-compute-510:
  Installé : 510.60.02-1pop0~1649099333~22.04~aedf526
  Candidat : 510.68.02-1pop0~1651161204~22.04~46a1f79
 Table de version :
     510.68.02-1pop0~1651161204~22.04~46a1f79 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
 *** 510.60.02-1pop0~1649099333~22.04~aedf526 100
        100 /var/lib/dpkg/status
     510.60.02-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages
libnvidia-decode-510:
  Installé : 510.60.02-1pop0~1649099333~22.04~aedf526
  Candidat : 510.68.02-1pop0~1651161204~22.04~46a1f79
 Table de version :
     510.68.02-1pop0~1651161204~22.04~46a1f79 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
 *** 510.60.02-1pop0~1649099333~22.04~aedf526 100
        100 /var/lib/dpkg/status
     510.60.02-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages
libnvidia-encode-510:
  Installé : 510.60.02-1pop0~1649099333~22.04~aedf526
  Candidat : 510.68.02-1pop0~1651161204~22.04~46a1f79
 Table de version :
     510.68.02-1pop0~1651161204~22.04~46a1f79 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
 *** 510.60.02-1pop0~1649099333~22.04~aedf526 100
        100 /var/lib/dpkg/status
     510.60.02-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages
libnvidia-fbc1-510:
  Installé : 510.60.02-1pop0~1649099333~22.04~aedf526
  Candidat : 510.68.02-1pop0~1651161204~22.04~46a1f79
 Table de version :
     510.68.02-1pop0~1651161204~22.04~46a1f79 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
 *** 510.60.02-1pop0~1649099333~22.04~aedf526 100
        100 /var/lib/dpkg/status
     510.60.02-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages
libnvidia-gl-510:
  Installé : 510.60.02-1pop0~1649099333~22.04~aedf526
  Candidat : 510.68.02-1pop0~1651161204~22.04~46a1f79
 Table de version :
     510.68.02-1pop0~1651161204~22.04~46a1f79 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
 *** 510.60.02-1pop0~1649099333~22.04~aedf526 100
        100 /var/lib/dpkg/status
     510.60.02-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages
```

**Issue/Bug Description:**
The Pop Shop offers me to install system updates but when I click on "update" the window closes instantly.
I tried to update in the terminal and all the packages that were upgradable got upgraded apart from those I listed above, apt said "The following packages have been kept back"

**Expected behavior:**
The update should proceed or at least show me an error dialog.

**Other Notes:**

Here is the output i got before the app crashes when running `$ G_MESSAGES_DEBUG=all io.elementary.appcenter &`

```
** (io.elementary.appcenter:10141): WARNING **: 18:24:47.480: Package.vala:567: Operation failed for package Mises à jour du système - The following packages have unmet dependencies:
  nvidia-driver-510: Dépend: nvidia-kernel-source-510 (= 510.60.02-1pop0~1649099333~22.04~aedf526) but 510.68.02-1pop0~1651161204~22.04~46a1f79 is to be installed
                     Dépend: libnvidia-extra-510 (= 510.60.02-1pop0~1649099333~22.04~aedf526) but 510.68.02-1pop0~1651161204~22.04~46a1f79 is to be installed
                     Dépend: nvidia-compute-utils-510 (= 510.60.02-1pop0~1649099333~22.04~aedf526) but 510.68.02-1pop0~1651161204~22.04~46a1f79 is to be installed
                     Dépend: nvidia-utils-510 (= 510.60.02-1pop0~1649099333~22.04~aedf526) but 510.68.02-1pop0~1651161204~22.04~46a1f79 is to be installed
                     Dépend: xserver-xorg-video-nvidia-510 (= 510.60.02-1pop0~1649099333~22.04~aedf526) but 510.68.02-1pop0~1651161204~22.04~46a1f79 is to be installed
                     Dépend: libnvidia-cfg1-510 (= 510.60.02-1pop0~1649099333~22.04~aedf526) but 510.68.02-1pop0~1651161204~22.04~46a1f79 is to be installed


(io.elementary.appcenter:10141): GLib-GObject-CRITICAL **: 18:24:47.482: g_value_get_pointer: assertion 'G_VALUE_HOLDS_POINTER (value)' failed
```

Feel free to ask if you need more details.

**Comment by leviport** [comment] 2022-05-02 15:43
Looks like a duplicate of https://github.com/pop-os/pop/issues/2304

**Closed by leviport** 2022-05-02 15:43 UTC
