### ISSUE TITLE
Adhere to Software and Updates update settings

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/shop#38] opened 2017-12-21 16:56 UTC
Honor user update choices. This should be considered in the context of the future use of Software and Updates. We have discussed removing it.

**Comment by isantop** [comment] 2017-12-21 17:04
I think a good long-term solution is to write our own repository management tool similar to software-properties-gtk but aimed at interacting with Pop Shop. software-properties-gtk seems to operate completely outside of gsettings, so having this work with Pop Shop will probably mean writing a configuration file parser of some kind.

**Comment by WatchMkr** [comment] 2017-12-21 17:13
Yeah, you're probably right. I searched through gsettings and didn't see anything for these options.

**Comment by isantop** [comment] 2017-12-21 17:27
@cassidyjames mentioned an app that was submitted to AppCenter in elementary that handles the repository list. It was rejected due to policy things, but that could be a really good jumping-off point.

**Comment by WatchMkr** [comment] 2017-12-21 17:31
Great, links?

**Comment by cassidyjames** [comment] 2017-12-21 17:33
https://github.com/mirkobrombin/PPAExtender

**Comment by WatchMkr** [comment] 2017-12-21 17:34
Maybe a good jumping off point. This functionality belongs in gnome settings though - rather than stand alone.

**Comment by cassidyjames** [comment] 2017-12-21 17:43
I raised a few questions in the context of this discussion this morning:

1. What problem does modifying when the system checks for updates actually solve?
2. Is there poor behavior that users are wanting to work around by changing when things get checked?

AppCenter was designed to be fiddle-free: it checks on log-in, plus when you open the app. I know there is some refinement that could be made, but the reasoning is that if a new app is released and users open the app store to look for it, it needs to automatically check to get the latest data. Not doing that means users have outdated repository information, especially in elementary OS where new apps are released every day.

Managing repositories is a completely different issue from checking for updates, though, and the two should not be confused.

**Comment by WatchMkr** [comment] 2017-12-21 18:05
All good points.

**Comment by jackpot51** [comment] 2017-12-21 18:13
For a user who wants to stop Pop!_Shop from giving notifications and checking for updates, this leaves only one course of action:

```
sudo apt-get purge pop-shop
```

**Comment by isantop** [comment] 2017-12-21 21:13
We should probably have an option in Pop Shop to disable update notifications. Due to the way Pop Shop operates, it doesn't really make sense to disable automatic update checking, but I can see the notifications being annoying if you prefer to do it manually.

**Comment by cassidyjames** [comment] 2017-12-21 21:49
Or if the issue is notifications, we throttle them intelligently to only show up once per day at most or something similar.

**Comment by brs17** [comment] 2018-05-18 20:57
Closing this issue as it was addressed with the creation of repoman. If a discussion regarding notifications or something else wants to be had, a new issue should be created (or discussed in the Pop!_Chat)

**Closed by brs17** 2018-05-18 20:57 UTC
